/*
 * MonitorFrame.java
 *
 * Created on June 14, 2006, 2:29 PM
 */

package za.co.turton.eyeburst;

import java.awt.Component;
import java.util.logging.Level;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.jfree.chart.JFreeChart;
import za.co.turton.eyeburst.config.Configuration;
import za.co.turton.eyeburst.config.ConfigurationException;

/**
 * This is the main Swing frame of the application
 * @author james
 */
public class MonitorFrame extends javax.swing.JFrame implements MonitorThreadListener {
    
    private MonitorThread monitorThread;
    
    private JFreeChart chart;
    
    private TowerTableModel towerTableModel;
    
    private ChartCanvas chartCanvas;
    
    /**
     * Creates a new MonitorFrame
     */
    public MonitorFrame() {
        initComponents();
//        settingsDialog.setContentPane(new SettingsPanel());
//        settingsDialog.pack();
        setTitle(Configuration.getAppTitle());
        this.towerTableModel = new TowerTableModel();
        TableSorter sorter = new TableSorter(towerTableModel);
        sorter.setTableHeader(towerTable.getTableHeader());
        towerTable.getTableHeader().setToolTipText("Click to specify sorting; Control-Click to specify secondary sorting");
        towerTable.setModel(sorter);
        towerTableModel.addTableModelListener(towerTable);
        chartCanvas = new ChartCanvas(towerTableModel);
        graphPanel.add(chartCanvas);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        errorDialog = new javax.swing.JDialog();
        errorLabel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        graphPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        towerTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        errorDialog.getContentPane().setLayout(new java.awt.FlowLayout());

        errorDialog.setTitle("Error");
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        errorDialog.setModal(true);
        errorDialog.setName("Error Dialogue");
        errorLabel.setText("Error");
        errorDialog.getContentPane().add(errorLabel);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eyeBurst");
        setName("eyeBurst Frame");
        displayPanel.setLayout(new java.awt.BorderLayout());

        displayPanel.setAutoscrolls(true);
        displayPanel.setMinimumSize(new java.awt.Dimension(400, 200));
        displayPanel.setOpaque(false);
        displayPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        graphPanel.setLayout(new javax.swing.BoxLayout(graphPanel, javax.swing.BoxLayout.X_AXIS));

        graphPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                graphPanelComponentResized(evt);
            }
        });

        jSplitPane1.setLeftComponent(graphPanel);

        towerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        towerTable.setGridColor(new java.awt.Color(192, 192, 192));
        tableScrollPane.setViewportView(towerTable);

        jSplitPane1.setRightComponent(tableScrollPane);

        displayPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(displayPanel);

        jLabel1.setText("Currently aligned to");
        jPanel1.add(jLabel1);

        jLabel2.setText("?");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1);

        connectButton.setText("Connect");
        connectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectButtonHandler(evt);
            }
        });

        buttonPanel.add(connectButton);

        resetButton.setText("Reset");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        buttonPanel.add(resetButton);

        getContentPane().add(buttonPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        towerTableModel.clear();
        chartCanvas.repaint();
    }//GEN-LAST:event_resetButtonMouseClicked
    
    private void graphPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_graphPanelComponentResized
        chartCanvas.setSize(graphPanel.getSize());
        chartCanvas.repaint();
    }//GEN-LAST:event_graphPanelComponentResized
    
    private void connectButtonHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButtonHandler
        JButton button = (JButton) evt.getSource();
        String action = button.getText();
        
        if (action.equals("Connect")) {
            button.setEnabled(false);
            monitorThread = new MonitorThread();
            monitorThread.addListener(this);
            monitorThread.start();
            
        } else if (action.equals("Disconnect")) {
            button.setEnabled(false);
            monitorThread.requestStop();
        }
    }//GEN-LAST:event_connectButtonHandler
    
    /**
     *
     * @see MonitorThreadListener#towerDatum
     */
    public void towerDatum(final MonitorThreadEvent event) {
        final TowerDatum towerDatum = event.getDatum();
        
        if (towerDatum.cost < Configuration.getSignalLowerBound())
            return;
        
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                towerTableModel.addTowerDatum(towerDatum);
                chartCanvas.repaint();
            }
        });
    }
    
    /**
     *
     * @see MonitorThreadListener#disconnected
     */
    public void disconnected(final MonitorThreadEvent e) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                connectButton.setText("Connect");
                connectButton.setEnabled(true);
            }
        });
    }
    
    /**
     *
     * @see MonitorThreadListener#currentTower
     */
    public void currentTower(final MonitorThreadEvent e) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jLabel2.setText(e.getCurrentTower().getName());
                connectButton.setEnabled(true);
            }
        });
    }
    
    /**
     *
     * @see MonitorThreadListener#connected
     */
    public void connected(final MonitorThreadEvent e) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                connectButton.setText("Disconnect");
                connectButton.setEnabled(true);
            }
        });
    }
    
    /**
     *
     * @see MonitorThreadListener#connectFailed
     */
    public void connectFailed(final MonitorThreadEvent e) {
        final Component dialogParent = this;
        
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JOptionPane.showMessageDialog(dialogParent, e.getThreadException(), "Error", JOptionPane.ERROR_MESSAGE);
                connectButton.setEnabled(true);
            }
        });
    }
    
    
    /**
     * Application execution entry point
     * @param args are ignored, configuration is loaded from a properties file
     */
    public static void main(String args[]) {
        
        try {
            Configuration.configure();
            
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    new MonitorFrame().setVisible(true);
                }
            });
        } catch (ConfigurationException e) {
            Configuration.getLogger().log(Level.SEVERE, "Could not configure eyeBurst", e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton connectButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton resetButton;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable towerTable;
    // End of variables declaration//GEN-END:variables
    
}
