/*
 * SettingsPanel.java
 *
 * Created on July 3, 2006, 3:03 PM
 */

package za.co.turton.eyeburst.config;

import java.util.logging.Level;
import javax.swing.ComboBoxModel;
import javax.swing.JDialog;
import javax.swing.event.ListDataListener;

/**
 * Panel for user configuration of eyeBurst settings
 * @author james
 */
public class SettingsPanel extends javax.swing.JPanel {
    
    private ComboBoxModel comboBoxModel;
    
    /**
     * Creates new SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        expiryLabel = new javax.swing.JLabel();
        expiry = new javax.swing.JSpinner();
        lowerBoundLabel = new javax.swing.JLabel();
        lowerBound = new javax.swing.JSpinner();
        loggerLabel = new javax.swing.JLabel();
        loggerLevel = new javax.swing.JComboBox();
        promptLabel = new javax.swing.JLabel();
        promptInterval = new javax.swing.JSpinner();
        connectTimeoutLabel = new javax.swing.JLabel();
        connectTimeout = new javax.swing.JSpinner();
        readTimeoutLabel = new javax.swing.JLabel();
        readTimeout = new javax.swing.JSpinner();
        utdAddressLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ipLabel = new javax.swing.JLabel();
        utdIPAddress = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        utdPort = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 10, 0));

        expiryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expiryLabel.setText("Chart Data Expiry (s)");
        expiryLabel.setName("chartDataExpiry");
        jPanel2.add(expiryLabel);

        expiry.setToolTipText("");
        expiry.setMaximumSize(new java.awt.Dimension(31, 32767));
        expiry.setValue(Configuration.getChartDataExpiry()/1000
        );
        jPanel2.add(expiry);

        lowerBoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lowerBoundLabel.setText("Suppress Data Weaker Than (dB)");
        lowerBoundLabel.setName("signalLowerBound");
        jPanel2.add(lowerBoundLabel);

        lowerBound.setMaximumSize(new java.awt.Dimension(31, 24));
        lowerBound.setValue(Configuration.getSignalLowerBound());
        jPanel2.add(lowerBound);

        loggerLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        loggerLabel.setText("Logging Level");
        loggerLabel.setName("loggerLevel");
        jPanel2.add(loggerLabel);

        loggerLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST" }));
        loggerLevel.setSelectedItem(Configuration.getLogger().getLevel().getName());
        jPanel2.add(loggerLevel);

        promptLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        promptLabel.setText("Current Tower Prompt Interval (ms)");
        promptLabel.setName("writerSleep");
        jPanel2.add(promptLabel);

        promptInterval.setValue(Configuration.getWriterSleep());
        jPanel2.add(promptInterval);

        connectTimeoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        connectTimeoutLabel.setText("Socket Connect Timeout (ms)");
        connectTimeoutLabel.setName("connectTimeout");
        jPanel2.add(connectTimeoutLabel);

        connectTimeout.setValue(Configuration.getConnectTimeout());
        jPanel2.add(connectTimeout);

        readTimeoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        readTimeoutLabel.setText("Socket Read Timeout (ms)");
        readTimeoutLabel.setName("readTimeout");
        jPanel2.add(readTimeoutLabel);

        readTimeout.setValue(Configuration.getReadTimeout());
        jPanel2.add(readTimeout);

        utdAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        utdAddressLabel.setText("UTD Address");
        utdAddressLabel.setName("utdIPAddress");
        jPanel2.add(utdAddressLabel);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ipLabel.setText("IP");
        jPanel1.add(ipLabel);

        utdIPAddress.setText(Configuration.getUtdIPAddress().getHostName());
        jPanel1.add(utdIPAddress);

        portLabel.setText("Port");
        jPanel1.add(portLabel);

        utdPort.setText(String.valueOf(Configuration.getUtdIPAddress().getPort()));
        jPanel1.add(utdPort);

        jPanel2.add(jPanel1);

        add(jPanel2);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel3.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        jPanel3.add(cancelButton);

        add(jPanel3);

    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            Configuration.transformAndSet(connectTimeoutLabel.getName(), connectTimeout.getValue().toString());
            Configuration.transformAndSet(loggerLabel.getName(), loggerLevel.getSelectedItem().toString());
            Configuration.transformAndSet(readTimeoutLabel.getName(), readTimeout.getValue().toString());
            Configuration.transformAndSet(expiryLabel.getName(), String.valueOf((Integer) expiry.getValue() * 1000));
            Configuration.transformAndSet(lowerBoundLabel.getName(), lowerBound.getValue().toString());
            Configuration.transformAndSet(utdAddressLabel.getName(), utdIPAddress.getText()+":"+utdPort.getText());
            Configuration.transformAndSet(promptLabel.getName(), promptInterval.getValue().toString());
        
        } catch (ConfigurationException e) {
            Configuration.getLogger().log(Level.WARNING, "Could not perform configuration", e);
        }
        
        getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JSpinner connectTimeout;
    private javax.swing.JLabel connectTimeoutLabel;
    private javax.swing.JSpinner expiry;
    private javax.swing.JLabel expiryLabel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loggerLabel;
    private javax.swing.JComboBox loggerLevel;
    private javax.swing.JSpinner lowerBound;
    private javax.swing.JLabel lowerBoundLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel portLabel;
    private javax.swing.JSpinner promptInterval;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JSpinner readTimeout;
    private javax.swing.JLabel readTimeoutLabel;
    private javax.swing.JLabel utdAddressLabel;
    private javax.swing.JTextField utdIPAddress;
    private javax.swing.JTextField utdPort;
    // End of variables declaration//GEN-END:variables
    
}
