/*
 * SampleFrame.java
 *
 * Created on August 1, 2006, 12:58 PM
 */

package za.co.turton.eyeburst.sample;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import za.co.turton.eyeburst.config.Configuration;
import za.co.turton.eyeburst.config.Inject;
import za.co.turton.eyeburst.config.InjectionConstructor;

/**
 *
 * @author  james
 */
public class SampleFrame extends javax.swing.JFrame {                
    
    private ChartPanel chartPanel;
    
    private int sampleSize;
    
    /**
     * Creates new form SampleFrame
     */
    public @InjectionConstructor SampleFrame(
            @Inject("chartPanel") ChartPanel chartPanel) {
        
        initComponents();                
        this.chartPanel = chartPanel;
        this.chartPanelContainer.add(chartPanel);
        pack();
    }    

    public void setSampleSize(int sampleSize) {
        if (sampleSize <= 0)
            throw new IllegalArgumentException("Sample size must be >= 1");
        
        this.sampleSize = sampleSize;
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        sampleGroupMenu = new javax.swing.JPopupMenu();
        createGroupItem = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        chartPanelContainer = new javax.swing.JPanel();
        pendingsPanel = new javax.swing.JPanel();
        promptLabel = new javax.swing.JLabel();

        sampleGroupMenu.setInvoker(pendingsPanel);
        sampleGroupMenu.setName("createGroupPopup");
        createGroupItem.setText("Create Sample Group");
        createGroupItem.setName("createSampleGroupItem");
        createGroupItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupItemActionPerformed(evt);
            }
        });

        sampleGroupMenu.add(createGroupItem);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("eyeBurst");
        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        chartPanelContainer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                chartPanelContainerComponentResized(evt);
            }
        });

        jSplitPane1.setLeftComponent(chartPanelContainer);

        pendingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Pending Samples", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pendingsPanel.setComponentPopupMenu(sampleGroupMenu);
        pendingsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingsPanelMouseClicked(evt);
            }
        });

        promptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promptLabel.setText("Right-click to create a sample group");
        promptLabel.setEnabled(false);
        promptLabel.setName("promptLabel");
        pendingsPanel.add(promptLabel);

        jSplitPane1.setRightComponent(pendingsPanel);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chartPanelContainerComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_chartPanelContainerComponentResized
        Dimension size = chartPanelContainer.getSize();
        chartPanel.setPreferredSize(new Dimension(size.width - 30, size.height - 10));
        chartPanel.setSize(new Dimension(size.width - 30, size.height - 10));
    }//GEN-LAST:event_chartPanelContainerComponentResized
    
    private void createGroupItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupItemActionPerformed
        String groupName = JOptionPane.showInputDialog(this, "Sample Group Name (e.g. Near Window)");
        
        if (groupName == null)
            return;
        
        for (Component child : pendingsPanel.getComponents()) {
            if (child.getName() != null && child.getName().equals(groupName))
                return;
        }
         
        if (pendingsPanel.getComponents()[0].getName().equals("promptLabel")) {
            pendingsPanel.removeAll();
            pendingsPanel.setLayout(new BoxLayout(pendingsPanel, BoxLayout.Y_AXIS));
        }
        
        SampleGroup sampleGroup = Configuration.configure(SampleGroup.class);
        sampleGroup.setGroupName(groupName);
        sampleGroup.setSampleSize(sampleSize);
        sampleGroup.addListener(chartPanel);
        
        SampleGroupPanel groupPanel = Configuration.configure(SampleGroupPanel.class);
        groupPanel.setName(groupName);
        groupPanel.setSampleGroup(sampleGroup);
        pendingsPanel.add(groupPanel);        
        groupPanel.setVisible(true);

        pack();
    }//GEN-LAST:event_createGroupItemActionPerformed
    
    private void pendingsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingsPanelMouseClicked
        // Dummy method necessary for popup menu
    }//GEN-LAST:event_pendingsPanelMouseClicked
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanelContainer;
    private javax.swing.JMenuItem createGroupItem;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pendingsPanel;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JPopupMenu sampleGroupMenu;
    // End of variables declaration//GEN-END:variables
    
}
