/*
 * SampleGroupPanel.java
 *
 * Created on August 14, 2006, 11:48 AM
 */

package za.co.turton.eyeburst.sample;

import java.awt.GridLayout;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingConstants;
import javax.swing.border.TitledBorder;
import za.co.turton.eyeburst.Tower;
import za.co.turton.eyeburst.TowerPublicationEvent;
import za.co.turton.eyeburst.TowerPublicationListener;
import za.co.turton.eyeburst.TowerPublisher;

/**
 *
 * @author  james
 */
public class SampleGroupPanel extends javax.swing.JPanel implements TowerPublicationListener, TowerCompletedListener {
    
    private SampleGroup sampleGroup;
    
    private Map<Tower, JProgressBar> progressBars;
    
    /** Creates new form SampleGroupPanel */
    public SampleGroupPanel(SampleGroup sampleGroup) {
        initComponents();
        this.sampleGroup = sampleGroup;
        ((TitledBorder) getBorder()).setTitle(sampleGroup.getGroupName());
        setTransferHandler(new TowerTransferHandler());
        this.progressBars = new HashMap<Tower, JProgressBar>();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public boolean addTower(String towerCode) {
        Tower tower = TowerPublisher.getInstance().createTower(towerCode);
        sampleGroup.add(tower);
        
        GridLayout layout = (GridLayout) getLayout();
        layout.setRows(layout.getRows()+1);
        
        JLabel towerLabel = new JLabel(tower.getName());
        towerLabel.setHorizontalAlignment(SwingConstants.CENTER);
        add(towerLabel);
        
        JProgressBar towerProgress = new JProgressBar(0, sampleGroup.getSampleSize());
        add(towerProgress);
        progressBars.put(tower, towerProgress);
        
        towerLabel.setVisible(true);
        towerProgress.setVisible(true);
        
//        getTopLevelAncestor().pack();
        repaint();
        
        return true;
    }
    
    public void towerPublication(TowerPublicationEvent evt) {
        String towerCode = evt.getTowerDatum().code;
        JProgressBar progressBar = progressBars.get(towerCode);
        
        if (progressBar != null)
            progressBar.setValue(progressBar.getValue() + 1);
    }
    
    public void towerCompleted(TowerCompletedEvent tc) {
        String towerCode = tc.getTower().getCode();
        JProgressBar progressBar = progressBars.get(towerCode);
        int index = Arrays.asList(getComponents()).indexOf(progressBar);
        remove(progressBar);
        remove(index - 1);
        
        GridLayout layout = (GridLayout) getLayout();
        layout.setRows(layout.getRows() - 1);
        progressBars.remove(towerCode);
//        pack();
        repaint();
    }
    
}
